USE [master]
GO

/****** Object:  Database [Timestar_ClientModel]    Script Date: 3/27/2025 12:36:12 PM ******/
CREATE DATABASE [Timestar_ClientModel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimeStar_ClientModel', FILENAME = N'F:\Data\Timestar_ClientModel.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'TimeStar_ClientModel_log', FILENAME = N'G:\Logs\Timestar_ClientModel_log.ldf' , SIZE = 1056768KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Timestar_ClientModel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Timestar_ClientModel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET ARITHABORT OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Timestar_ClientModel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Timestar_ClientModel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Timestar_ClientModel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Timestar_ClientModel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET RECOVERY FULL 
GO

ALTER DATABASE [Timestar_ClientModel] SET  MULTI_USER 
GO

ALTER DATABASE [Timestar_ClientModel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Timestar_ClientModel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Timestar_ClientModel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Timestar_ClientModel] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Timestar_ClientModel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Timestar_ClientModel] SET QUERY_STORE = OFF
GO

USE [Timestar_ClientModel]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Timestar_ClientModel] SET  READ_WRITE 
GO


