/* Find a column in a database */
--USE SLIS;
--GO
SELECT TABLE_CATALOG,
       TABLE_SCHEMA,
       TABLE_NAME,
       COLUMN_NAME,
       DATA_TYPE,
       CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE 'Create%'
   --OR CHARACTER_MAXIMUM_LENGTH = 200;
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME;