/* Get table properties */
SELECT [name]
      ,[object_id]
      ,[principal_id]
      ,[schema_id]
      ,[parent_object_id]
      ,[type]
      ,[type_desc]
      ,[create_date]
      ,[modify_date]
      ,[is_ms_shipped]
      ,[is_published]
      ,[is_schema_published]
      ,[lob_data_space_id]
      ,[filestream_data_space_id]
      ,[max_column_id_used]
      ,[lock_on_bulk_load]
      ,[uses_ansi_nulls]
      ,[is_replicated]
      ,[has_replication_filter]
      ,[is_merge_published]
      ,[is_sync_tran_subscribed]
      ,[has_unchecked_assembly_data]
      ,[text_in_row_limit]
      ,[large_value_types_out_of_row]
      ,[is_tracked_by_cdc]
      ,[lock_escalation]
      ,[lock_escalation_desc]
      ,[is_filetable]
      ,[is_memory_optimized]
      ,[durability]
      ,[durability_desc]
      ,[temporal_type]
      ,[temporal_type_desc]
      ,[history_table_id]
      ,[is_remote_data_archive_enabled]
      ,[is_external]
      ,[history_retention_period]
      ,[history_retention_period_unit]
      ,[history_retention_period_unit_desc]
      ,[is_node]
      ,[is_edge]
      ,[data_retention_period]
      ,[data_retention_period_unit]
      ,[data_retention_period_unit_desc]
      ,[ledger_type]
      ,[ledger_type_desc]
      ,[ledger_view_id]
      ,[is_dropped_ledger_table]
  FROM [SLIS].[sys].[tables]
WHERE [name] = 'tablename'
  AND schema_id = SCHEMA_ID('dbo');